version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Ajoute cette ligne pour exposer Kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kafka  # Ajout de la base de données
    ports:
      - "5432:5432"
    networks:
      - kafka-network
    volumes:
      - db:/var/lib/postgresql/data
  app :
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-app
    ports:
      - "8081:8080"
    networks:
      - kafka-network
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
volumes:
  db:

networks:
  kafka-network:
    driver: bridge
