apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app-front
  labels:
    app: kafka-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app-front
  template:
    metadata:
      labels:
        app: kafka-app-front
    spec:
      containers:
        - name: kafka-app-front
          image: localhost:5000/kafka-app-front
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-app-front
spec:
  selector:
    app: kafka-app-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort